// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransferLogService.EntityFramework;

namespace TransferLogService.Migrations
{
    [DbContext(typeof(TransferMigrationsDbContext))]
    [Migration("20200330183106_Multitenancy")]
    partial class Multitenancy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AbpMicroRabbit.Banking.Domain.Entities.TransferLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FromAccount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ToAccount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("TransferAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("TransferLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af46fed8-d7af-4d54-9b48-1700423828d1"),
                            ConcurrencyStamp = "90cd2d72401f4a4791e45a1dbee9513f",
                            ExtraProperties = "{}",
                            FromAccount = "1231231201-313-131",
                            TenantId = new Guid("9fcc4ade-21e5-4686-a1ba-36aff25e5d0f"),
                            ToAccount = "1231231201-313-132",
                            TransferAmount = 100m
                        },
                        new
                        {
                            Id = new Guid("564a6dc1-6988-46e3-8a5a-7d31e90c5288"),
                            ConcurrencyStamp = "94f1f43e6af84a08a2c661f4ecf04160",
                            ExtraProperties = "{}",
                            FromAccount = "1231231201-313-131",
                            TenantId = new Guid("9fcc4ade-21e5-4686-a1ba-36aff25e5d0f"),
                            ToAccount = "1231231201-313-132",
                            TransferAmount = 100m
                        },
                        new
                        {
                            Id = new Guid("248b01a6-8e1e-42bf-804b-284eaf9705dd"),
                            ConcurrencyStamp = "c67f74de4b4043a58df1ebaf02b8e2db",
                            ExtraProperties = "{}",
                            FromAccount = "1231231201-313-131",
                            TenantId = new Guid("68d3a738-2918-4b1d-a293-71e9aaff8024"),
                            ToAccount = "1231231201-313-132",
                            TransferAmount = 100m
                        },
                        new
                        {
                            Id = new Guid("03eb804c-deba-47a1-ba69-7c9f18983d46"),
                            ConcurrencyStamp = "e673663a8c744993a4a257ef5d776b76",
                            ExtraProperties = "{}",
                            FromAccount = "1231231201-313-131",
                            TenantId = new Guid("68d3a738-2918-4b1d-a293-71e9aaff8024"),
                            ToAccount = "1231231201-313-132",
                            TransferAmount = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
