// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransferLogService.EntityFramework;

namespace TransferLogService.Migrations
{
    [DbContext(typeof(TransferMigrationsDbContext))]
    partial class TransferMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AbpMicroRabbit.Banking.Domain.Entities.TransferLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FromAccount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ToAccount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("TransferAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("TransferLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("168cd017-280a-4b38-913a-dd3426d88058"),
                            ConcurrencyStamp = "1ac2a725176549f487524e9cd00bc734",
                            ExtraProperties = "{}",
                            FromAccount = "1231231201-313-131",
                            ToAccount = "1231231201-313-132",
                            TransferAmount = 100m
                        },
                        new
                        {
                            Id = new Guid("77dbd3f9-6dde-484a-b4d0-c725c4b998d5"),
                            ConcurrencyStamp = "5e5129aa7ec4405d914f858f522b3c77",
                            ExtraProperties = "{}",
                            FromAccount = "1231231201-313-131",
                            ToAccount = "1231231201-313-132",
                            TransferAmount = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
