// <auto-generated />
using System;
using BankingService.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankingService.Migrations
{
    [DbContext(typeof(BankingMigrationsDbContext))]
    [Migration("20200320185747_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AbpMicroRabbit.Banking.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AccountType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cf8ac09-7f7a-45b1-880d-1234f30fbd84"),
                            AccountBalance = 100m,
                            AccountType = "Poupança",
                            ConcurrencyStamp = "a50c4f980beb4ebaac30a00a7bf75b7d",
                            ExtraProperties = "{}"
                        },
                        new
                        {
                            Id = new Guid("d337dafa-467f-4eb6-a064-58634e6bfdb8"),
                            AccountBalance = 200m,
                            AccountType = "Credito",
                            ConcurrencyStamp = "180400348f344a20bc42b96c19478ff3",
                            ExtraProperties = "{}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
