// <auto-generated />
using System;
using BankingService.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankingService.Migrations
{
    [DbContext(typeof(BankingMigrationsDbContext))]
    [Migration("20200330182105_Multitenancy")]
    partial class Multitenancy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AbpMicroRabbit.Banking.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AccountType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c622431b-8807-4e0d-bf53-a9ff0fdbd1cc"),
                            AccountBalance = 100m,
                            AccountType = "Poupança",
                            ConcurrencyStamp = "ee269e17ac3844fd8c818b5f3ccc79f5",
                            ExtraProperties = "{}",
                            TenantId = new Guid("9fcc4ade-21e5-4686-a1ba-36aff25e5d0f")
                        },
                        new
                        {
                            Id = new Guid("4f4afd13-c5a8-4b7c-9b7a-cd351f9bdcb6"),
                            AccountBalance = 200m,
                            AccountType = "Credito",
                            ConcurrencyStamp = "c094c90e30cb4464a210723712c9388f",
                            ExtraProperties = "{}",
                            TenantId = new Guid("9fcc4ade-21e5-4686-a1ba-36aff25e5d0f")
                        },
                        new
                        {
                            Id = new Guid("2189d7d3-a8b6-45a6-bada-3a8acef4bc94"),
                            AccountBalance = 100m,
                            AccountType = "Poupança",
                            ConcurrencyStamp = "2cac11a60e404e0f9f39f51f6192027f",
                            ExtraProperties = "{}",
                            TenantId = new Guid("68d3a738-2918-4b1d-a293-71e9aaff8024")
                        },
                        new
                        {
                            Id = new Guid("ba5d66de-3828-496b-bffe-7829c5cc103a"),
                            AccountBalance = 200m,
                            AccountType = "Credito",
                            ConcurrencyStamp = "f265c88809cb4eb59439015c093f416c",
                            ExtraProperties = "{}",
                            TenantId = new Guid("68d3a738-2918-4b1d-a293-71e9aaff8024")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
